DROP DATABASE IF EXISTS totesys_datawarehouse;
CREATE DATABASE totesys_datawarehouse;

-- Connect to the newly created database
\c totesys_datawarehouse

-- --- Create Dimension Tables First ---

CREATE TABLE "dim_date" (
  "date_id" date PRIMARY KEY NOT NULL,
  "year" int NOT NULL,
  "month" int NOT NULL,
  "day" int NOT NULL,
  "day_of_week" int NOT NULL,
  "day_name" varchar NOT NULL,
  "month_name" varchar NOT NULL,
  "quarter" int NOT NULL
);

CREATE TABLE "dim_staff" (
  "staff_id" int PRIMARY KEY NOT NULL,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "department_name" varchar NOT NULL,
  "location" varchar NOT NULL,
  "email_address" varchar NOT NULL
);

CREATE TABLE "dim_location" (
  "location_id" int PRIMARY KEY NOT NULL,
  "address_line_1" varchar NOT NULL,
  "address_line_2" varchar,
  "district" varchar,
  "city" varchar NOT NULL,
  "postal_code" varchar NOT NULL,
  "country" varchar NOT NULL,
  "phone" varchar NOT NULL
);

CREATE TABLE "dim_currency" (
  "currency_id" int PRIMARY KEY NOT NULL,
  "currency_code" varchar NOT NULL,
  "currency_name" varchar NOT NULL
);

CREATE TABLE "dim_design" (
  "design_id" int PRIMARY KEY NOT NULL,
  "design_name" varchar NOT NULL,
  "file_location" varchar NOT NULL,
  "file_name" varchar NOT NULL
);

CREATE TABLE "dim_counterparty" (
  "counterparty_id" int PRIMARY KEY NOT NULL,
  "counterparty_legal_name" varchar NOT NULL,
  "counterparty_legal_address_line_1" varchar NOT NULL,
  "counterparty_legal_address_line_2" varchar,
  "counterparty_legal_district" varchar,
  "counterparty_legal_city" varchar NOT NULL,
  "counterparty_legal_postal_code" varchar NOT NULL,
  "counterparty_legal_country" varchar NOT NULL,
  "counterparty_legal_phone_number" varchar NOT NULL
);

CREATE TABLE "dim_payment_type" (
  "payment_type_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "payment_type_name" varchar NOT NULL
);

CREATE TABLE "dim_transaction" (
  "transaction_id" int PRIMARY KEY NOT NULL,
  "transaction_type" varchar NOT NULL,
  "sales_order_id" int,
  "purchase_order_id" int
);

-- --- Create Fact Tables Second (since they reference dimension tables) ---

CREATE TABLE "fact_sales_order" (
  "sales_record_id" SERIAL PRIMARY KEY,
  "sales_order_id" int NOT NULL,
  "created_date" date NOT NULL REFERENCES "dim_date" ("date_id"),
  "created_time" time NOT NULL,
  "last_updated_date" date NOT NULL REFERENCES "dim_date" ("date_id"),
  "last_updated_time" time NOT NULL,
  "sales_staff_id" int NOT NULL REFERENCES "dim_staff" ("staff_id"),
  "counterparty_id" int NOT NULL REFERENCES "dim_counterparty" ("counterparty_id"),
  "units_sold" int NOT NULL,
  "unit_price" numeric(10, 2) NOT NULL, -- Corrected: Removed quotes
  "currency_id" int NOT NULL REFERENCES "dim_currency" ("currency_id"),
  "design_id" int NOT NULL REFERENCES "dim_design" ("design_id"),
  "agreed_payment_date" date NOT NULL REFERENCES "dim_date" ("date_id"),
  "agreed_delivery_date" date NOT NULL REFERENCES "dim_date" ("date_id"),
  "agreed_delivery_location_id" int NOT NULL REFERENCES "dim_location" ("location_id")
);

CREATE TABLE "fact_purchase_order" (
  "purchase_record_id" SERIAL PRIMARY KEY,
  "purchase_order_id" INT NOT NULL,
  "created_date" date NOT NULL REFERENCES "dim_date" ("date_id"),
  "created_time" time NOT NULL,
  "last_updated_date" date NOT NULL REFERENCES "dim_date" ("date_id"),
  "last_updated_time" time NOT NULL,
  "staff_id" int NOT NULL REFERENCES "dim_staff" ("staff_id"),
  "counterparty_id" int NOT NULL REFERENCES "dim_counterparty" ("counterparty_id"),
  "item_code" varchar NOT NULL,
  "item_quantity" int NOT NULL,
  "item_unit_price" numeric NOT NULL, -- Corrected: Removed quotes
  "currency_id" int NOT NULL REFERENCES "dim_currency" ("currency_id"),
  "agreed_delivery_date" date NOT NULL REFERENCES "dim_date" ("date_id"),
  "agreed_payment_date" date NOT NULL REFERENCES "dim_date" ("date_id"),
  "agreed_delivery_location_id" int NOT NULL REFERENCES "dim_location" ("location_id")
);

CREATE TABLE "fact_payment" (
  "payment_record_id" SERIAL PRIMARY KEY,
  "payment_id" int NOT NULL,
  "created_date" date NOT NULL REFERENCES "dim_date" ("date_id"),
  "created_time" time NOT NULL,
  "last_updated_date" date NOT NULL REFERENCES "dim_date" ("date_id"),
  "last_updated_time" time NOT NULL,
  "transaction_id" int NOT NULL REFERENCES "dim_transaction" ("transaction_id"),
  "counterparty_id" int NOT NULL REFERENCES "dim_counterparty" ("counterparty_id"),
  "payment_amount" numeric NOT NULL, -- Corrected: Removed quotes
  "currency_id" int NOT NULL REFERENCES "dim_currency" ("currency_id"),
  "payment_type_id" int NOT NULL REFERENCES "dim_payment_type" ("payment_type_id"),
  "paid" boolean NOT NULL,
  "payment_date" date NOT NULL REFERENCES "dim_date" ("date_id")
);