name: Royal Blue CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-tests:
    name: Run Python tests, check test coverage, check formatting and security scan
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Checkout Github repo
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.8"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Run uv sync
        run: uv sync --frozen

      - name: Run Ruff Lint
        run: uv run ruff check --fix --output-format=github .

      - name: Run Ruff Format
        run: uv run ruff format --verbose .

      - name: Run Tests with Coverage
        env:
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_DATABASE: ${{secrets.DB_DATABASE}}
          DB_PORT: ${{secrets.DB_PORT}}
        run: uv run pytest --cov=src tests/

      - name: Run Bandit Security Scan
        run: uv run bandit -r -lll src
  
  deploy-terraform:
    # if: github.event_name == 'workflow_dispatch'
    name: Deploy Royal Blue Terraform infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github repo
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.8"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Run uv sync
        run: uv sync --frozen

      - name: Create Lambda Layer bundle
        run: uv run ./build_lambda_layer.sh

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_DEFAULT_REGION}}
          
      - name: terraform format
        working-directory: terraform
        run: terraform fmt -recursive
      - name: terraform init
        working-directory: terraform
        run: terraform init
      - name: terraform plan
        working-directory: terraform
        env:
          TF_VAR_DB_USER: ${{secrets.DB_USER}}
          TF_VAR_DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          TF_VAR_DB_HOST: ${{secrets.DB_HOST}}
          TF_VAR_DB_DATABASE: ${{secrets.DB_DATABASE}}
          TF_VAR_DB_PORT: ${{secrets.DB_PORT}}
        run: terraform plan
      - name: terraform apply
        working-directory: terraform
        env:
          TF_VAR_DB_USER: ${{secrets.DB_USER}}
          TF_VAR_DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          TF_VAR_DB_HOST: ${{secrets.DB_HOST}}
          TF_VAR_DB_DATABASE: ${{secrets.DB_DATABASE}}
          TF_VAR_DB_PORT: ${{secrets.DB_PORT}}
        run: terraform apply -auto-approve